apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: r6osoub3k-go 
  janus-idp.io/tekton: r6osoub3k-go
  backstage.io/kubernetes-id: r6osoub3k-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: r6osoub3k-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml